#!/bin/bash
set -e

cd "$(dirname "$0")"

echo "Building Pickr..."
swift build -c release 2>&1

BINARY=".build/release/Pickr"
APP="Pickr.app"
CONTENTS="$APP/Contents"
MACOS="$CONTENTS/MacOS"
RESOURCES="$CONTENTS/Resources"

rm -rf "$APP"
mkdir -p "$MACOS"
mkdir -p "$RESOURCES"

cp "$BINARY" "$MACOS/Pickr"
cp "Info.plist" "$CONTENTS/Info.plist"

# Copy resource bundles (generated by SPM for assets / package resources)
for bundle in .build/release/*.bundle; do
    [ -d "$bundle" ] && cp -R "$bundle" "$RESOURCES/"
done

if [ -f "Resources/AppIcon.icns" ]; then
    cp "Resources/AppIcon.icns" "$RESOURCES/AppIcon.icns"
fi

echo ""
echo "Done! Pickr.app is ready."
echo "Run:  open Pickr.app"
